### ISSUE TITLE
大佬，介个解析出来会少字母撒。

### ISSUE THREAD

**Issue by Jinxiansen** [nixzhu/Baby#1]
<img width="862" alt="t" src="https://cloud.githubusercontent.com/assets/16829428/25517241/05b0cef4-2c21-11e7-8ded-ddde5368a9ea.png">

如图所示，ticketlist 会少了最后的 t 。

**Comment by Jinxiansen** [comment]
{
    "result": true,
    "resultcode": "shcl",
    "resultstring": "",
    "oauthtype": "",
    "oauthrate": "1",
    "ticketlist": [
        {
            "mainproductid": 483,
            "mainproductname": "水蜜桃健身",
            "mainproductshortname": "水蜜桃健身",
            "goodssalestartdate": "2016/7/19 0:00:00",
            "goodssaleenddate": "2017/7/20 0:00:00"
        }
    ]
}



json。

**Comment by nixzhu** [comment]
这是一个不完美的优化导致的：假设Array对应的Key是复数形式，例如`tickets`。之后可能会增加选项来避免。

**Comment by Jinxiansen** [comment]
好嘞，感谢大佬！
我是看着你的blog长大的。😂

**Comment by 457020372** [comment]
软件很好
