### ISSUE TITLE
[Feature Suggestion] Allow using `convertFromSnakeCase` strategy instead of CodingKeys

### ISSUE THREAD

**Issue by ApolloZhu** [nixzhu/Baby#16]
It's not really a problem, but I think this is a great feature that you might want to implement. See the following link for more details.

https://developer.apple.com/documentation/foundation/jsondecoder.keydecodingstrategy/2949105-convertfromsnakecase

**Comment by nixzhu** [comment]
@ApolloZhu It’s on my todo list.

**Comment by nixzhu** [comment]
@ApolloZhu Baby version 0.31.0 has a new option `--convert-from-snake-case` can helps you.
